#!/usr/bin/env python3

import sys
from n4d import client
import ipaddress
supported_methods = ['dhcp4-change','dhcp6-change']
args = sys.argv[1:]
try:
    if ( args[1] in supported_methods ) :
        with open('/etc/n4d/key','r') as fd:
            mk = fd.read().strip()
        c = client.Client(address='https://127.0.0.1:9779',key=mk)
        network_string = c.get_variable('LLIUREX_VLAN')
        network = ipaddress.ip_network(network_string)
        list_servers = list(map(str, list(network.hosts())[:-10:-1]))
        c.set_variable('EPOPTES_SERVERS',list_servers)
    else:
        print("Method " + str(args) + " not supported \n")
except Exception as e:
        print("Error on set epoptes variable" + str(e) )
