#! /usr/bin/python3

import sys

sys.path.append('/usr/share/epoptes-client-register/')

import EpoptesClientRegister

if __name__=="__main__":
	args={}
	args["gui"]=True
	args["server"]="localhost"
	ls=EpoptesClientRegister.EpoptesClientRegister(args)